### ISSUE TITLE
Runtime Error in example_heatmap_rendering.py

### ISSUE THREAD

**Issue by RALaFrance222** [sandialabs/tracktable#2]
https://github.com/sandialabs/tracktable/blob/70141b6bb6c6c2d160e3832f81bbf65ad2c2f2fe/tracktable/Python/tracktable/examples/example_heatmap_rendering.py#L76

The referenced line previously worked because heatmap_from_points was imported "as heatmap".  I guess when heatmap_from_points was removed, this line was not updated to refer to whatever the replacement is

**Comment by atwilso** [comment]
Many of the examples got moved aside when we started to use Jupyter notebooks.  I have a local branch that restores them.  The good news is that the examples are now fully self-contained so this problem shouldn't recur.

**Comment by mjfadem** [comment]
With the recent overhaul of the examples and tutorials in version 1.6 this shouldn't be an issue anymore.
